### ISSUE TITLE
Aanmeldingsformulier clubrecord

### ISSUE THREAD

**Issue by avdeliemers** [p4m/avdl#4]
Leden moeten nieuwe clubrecords kunnen aanmelden. In alle besprekingen hebben we het er één keer kort over gehad maar daarna heb ik er helemaal niet meer aan gedacht.
Het mag een nieuwe pagina zijn of een item onderaan de pagina met clubrecords. De tekst onder de streepjes moet in ieder geval getoond worden.
Het aanmeldformulier moet de volgende items bevatten en de output moet via mail naar clubrecord@avdeliemers.nl
----------------------------------
Items voor aanmeldformulier, alle velden mogen vrij in te vullen zijn:
---------------------------------
Naam: 
Geboortedatum: 
Geslacht: 
Email: 
Categorie: 
Onderdeel: 
Prestatie: 
Datumwedstrijd: 
Plaatswedstrijd: 
Wedstrijdsoort: 
Linkwebsite uitslag: 
Opmerkingen: 

---------------------------------------------------------------
Tekst te verduidelijking
-----------------------------------------------------------------
Regels met betrekking tot de clubrecords: 
Algemeen: 
- Alleen de leden van AV de Liemers kunnen clubrecords vestigen.
- De prestatie staat vermeldt in een officiële uitslag.
- De afstanden/leeftijdscategorieën waar nog geen clubrecord voor geregistreerd is zijn vacant totdat er door een AVL atleet een prestatie neergezet wordt. 
- Leden van AV de Liemers mogen ook prestaties uit het verleden aanmelden mits deze verifieerbaar zijn en voldoen aan de gestelde criteria.

Baanonderdelen: 
- Alleen clubrecords op officiële, reguliere onderdelen worden vermeld (vanaf junioren D). 
- Vanaf de B junioren geldt de eis van windmeting op de sprint- en springonderdelen waarbij dat gangbaar is (zijnde sprintnummers t/m 200m, verspringen en hinkstapspringen). Het windvoordeel mag niet meer zijn dan 2 m/sec. 
- Tevens is vanaf de B junioren elektronische tijd vereist op de sprintonderdelen. Bij handgemeten tijd op de sprintonderdelen tot 400m wordt 0.24 sec opgeteld om de prestatie te vergelijken met elektronische tijd, bij de 400m is dit 0.14 sec. Voor alle andere afstanden vindt geen correctie plaats.

Wegonderdelen: 
- In principe geldt de eis dat de prestatie moet zijn behaald op een gecertificeerd parcours. Hier kan men zien welke parcoursen gecertificeerd zijn. Bij elk gecertificeerd loopevenement wordt dit aangeduid met het symbool 'meetlint'.
- Als er op een niet-gecertificeerd parcours (maar wel KNAU-wedstrijd) sneller wordt gelopen dan het bestaande CR (of als het onderdeel nog vacant stond), zal die prestatie vermeld worden als CR, maar wel met een noot erbij dat het hier geen gecertificeerd parcours betreft. Deze vermelding komt dus naast een eventueel bestaand CR welke langzamer was maar wel een gecertificeerd parcours betrof. 
- Wanneer er alleen een CR staat dat is gelopen op een niet-gecertificeerd parcours, kunnen altijd langzamere prestaties worden aangemeld die wel op een gecertificeerd parcours zijn gelopen (dus dan weer een dubbele vermelding).

Record verbeterd? 
U kunt een formulier invullen om een clubrecord aan te melden. 
Voor vragen kunt u een e-mail sturen naar clubrecord@avdeliemers.nl.

**Comment by p4m** [comment]
Het is uitgevoerd zoals gevraagd.

Onderaan de pagina:
[avdliemers.publishpath.com/club-en-baanrecords-av-de-liemers](http://avdliemers.publishpath.com/club-en-baanrecords-av-de-liemers)

Deze pagina is een blog-artikel. De pagina wordt geopend in een nieuwe pagina die in de hiërarchie onder de pagina [wedstrijden](http://avdeliemers.publishpath.com/wedstrijden) is gehangen.

Deze nieuwe pagina heet clubrecords en wordt als detailpagina gebruikt (zoals opgezet bij [nieuws](http://avdliemers.publishpath.com/nieuws)):
[avdliemers.publishpath.com/clubrecords](http://avdliemers.publishpath.com/clubrecords)

De pagina [clubrecords](http://avdliemers.publishpath.com/clubrecords) is via het menu niet rechtstreeks te benaderen.

**Comment by avdeliemers** [comment]
In Firefox wordt het veld geboortedatum en datum van de wedstrijd niet goed weergegeven. Dit zijn 3 velden onderelkaar die niet duidelijk aangeven wat er ingevuld moet worden.
Kan je dit herstellen?

**Comment by p4m** [comment]
Kan het zijn dat je je browser nog moet verversen met nieuwe broncode. E.e.a. is namelijk aangepast zodat het er cosmetisch zo uit ziet, zoals het er nu uitziet. Ik heb browsers tests uitgevoerd in FireFox op Mac en op Windows (zie [schermafdruk](http://app.crossbrowsertesting.com/public/i28bc053cc22e7ad/livetests/3784788/snapshots/z91d5969dfd3898d5ded)); daar werkt het goed.

**Comment by avdeliemers** [comment]
Firefox voor windows is nu ook goed.
