### ISSUE TITLE
Algemene informatie - Adressen en Locaties

### ISSUE THREAD

**Issue by avdeliemers** [p4m/avdl#5]
Ik heb in de rode navigatiebalk op de pagina "Algemene Informatie" een extra item gemaakt met Adressen en locaties. Ik zie echter nergens waar ik de link/anker kan aanmaken om direct naar dit deel van de pagina te gaan.

**Comment by p4m** [comment]
Om een dergelijk link naar te maken moet bij de doel-tekst eerst een anchor geplaatst worden.

Een anchor kan via de rich text editor, of in de html-weergave:
`<a name="adressen" id="adressen" class="target"></a>`

In het submenu kun je dan verwijzen met (in dit geval) #adressen

    <ul class="nav submenu">
        <li><a href="#wedstrijdkleding">Wedstrijdkleding</a></li>
        <li><a href="#clubkleding">Clubkleding</a></li>
        <li><a href="#vesten">Vesten</a></li>
        <li><a href="#adressen-en-commissies">Bestuur en Commissies</a></li>
        <li><a href="#adressen">Adressen en Locaties</a></li>
    </ul>

**Comment by p4m** [comment]
Schermafdrukken ter illustratie en verduidelijking.

Anchor aanmaken bij doel:




In het menu een link maken naar het anchor.


​
​
​

Groet,

Frank Welten

: publiceervoormij.nl

Wildenborchallee 43
6921 JZ  Duiven
06-54970030
www.linkedin.com/in/frankwelten


Op 5 oktober 2015 18:23 schreef avdeliemers <notifications@github.com>:
