### ISSUE TITLE
Witlijntje tussen navigatiebalken

### ISSUE THREAD

**Issue by avdeliemers** [p4m/avdl#6]
Tussen de blauwe en rode navigatiebalk is een klein wit lijntje zichtbaar. Dit is mooi en mag blijven.
Als er gescrolled wordt dan komen de tekst en de afbeeldingen door deze lijn heen. De lijn is blijkbaar transparant. 
Kan de lijn een vaste witte kleur krijgen zodat tijdens het scrollen de tekst e.d. er niet doorheen komt?

**Comment by p4m** [comment]
Het was idd bewust dat er 1px ruimte werd gehouden tussen het hoofdmenu en submenu; gaf een ruimtelijk effect. De stijl aangepast zodat deze ruimte opgevuld wordt met 1px witte lijn.

**Comment by avdeliemers** [comment]
Het is nog geen vast wit lijntje. Het is nog steeds transparant waardoor de tekst erdoor scrollt.
Het witte lijntje vind ik mooi en geeft inderdaad een ruimtelijk effect maar het transparante moet er dan wel uit s.v.p.

**Comment by p4m** [comment]
Sorry, schijnbaar mijn code overschreven. Nu opnieuw aangepast en is zichtbaar (na verversen van browser).
